src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $booker = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ad $ad = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\GreaterThan("today",message: "La date d'arrivée doit être ultérieur à la date d'aujourd'hui", groups:["front"])] // la date doit être plus grand qu'aujourd'hui
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\GreaterThan(propertyPath:"startDate", message:"La date de départ doit être plus éloignée que la date d'arrivée")] // plus grand que la date d'arrivée
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column]
    private ?float $amount = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comment = null;

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function prePersist(): void
    {
        if(empty($this->createdAt))
        {
            $this->createdAt = new \DateTime();
        }
        if(empty($this->amount))
        {
            // prix de l'annonce * nombre de jours
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    /**
     * Permet de récupérer le nombre de jour d'une réservation
     *
     * @return integer|null
     */
    public function getDuration(): ?int
    {
        //la méthode diff des objets datetime fait la différence entre 2 date et renvoie un objet de type DateInterval

        $diff = $this->endDate->diff($this->startDate);
        // récup un objet de type DateInterval et pour récup le jour 
        return $diff->days; // récupère le nombre de jour entre 2 dates
    }


    /**
     * Permet de vérifier si les dates sont réservables
     *
     * @return boolean
     */
    public function isBookableDates(): bool
    {
        // connaitre les dates impossible pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays(); // on réupère les jours qu"on a récupéré dans Entity Ad avec la function getNotAvailableDays
        // comparer les dates choisies avec les dates impossible
        $bookingDays = $this->getDays();

        //transformation des objets dateTime en tableau de chaines de caractères pour les journées ( facilite la comparaison )
        // on récupère les jours sélectionnés
        $days = array_map(function($day){
            return $day->format('Y-m-d');
        },$bookingDays);

        // on récupère les jours non disponibles
        $notAvailable = array_map(function($day){
            return $day->format('Y-m-d');
        },$notAvailableDays);

        // si il y a un match entre les deux on return false
        foreach($days as $day){
            if(array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Permet de récupérer un tableau des journées qui correspondent à ma réservation
     *
     * @return array|null Un tableau d'objets DateTime représentant les jours de la réservation
     */
    public function getDays(): ?array
    {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24*60*60
        );
        $days = array_map(function($dayTimestamp){
            return new \DateTime(date('Y-m-d',$dayTimestamp));
        },$resultat);

        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): static
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): static
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields:['email'],message: "Un autre utilisateur possède déjà cette adresse e-mail, merci de la modifier")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(message: "Veuillez renseigner une adresse e-mail valide")]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotBlank(message:"Veuillez renseigner un mot de passe")] // on ne peut pas le laisser vide
    private ?string $password = null;

    #[Assert\EqualTo(propertyPath:"password", message:"Vous n'avez pas correctement confirmé votre mot de passe")]
    public ?string $passwordConfirm = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Veuillez renseigner votre prénom")]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Veuillez renseigner votre nom de famille")]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Image(mimeTypes:['image/png','image/jpeg', 'image/jpg', 'image/gif'], mimeTypesMessage:"Vous devez upload un fichier jpg, jpeg, png ou gif")]
    #[Assert\File(maxSize:"1024k", maxSizeMessage: "La taille du fichier est trop grande")]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min:10,max:255, minMessage:"Votre introduction doit faire plus de 10 caractères", maxMessage:"Votre introduction ne doit pas faire plus de 255 caractères")]
    private ?string $introduction = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min:100, minMessage:"Votre description doit faire plus de 100 caractères")]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Ad::class)]
    private Collection $ads;

    #[ORM\OneToMany(mappedBy: 'booker', targetEntity: Booking::class)]
    private Collection $bookings;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet de créer un slug automatiquement avec le nom et prénom de l'utilisateur
     *
     * @return void
     */
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug(): void
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName.' '.uniqid());
        }
    }

    /**
     * Permet d'obtenir le nom complet de l'utilisateur
     *
     * @return string
     */
    public function getFullName(): string
    {
        return $this->firstName." ".$this->lastName;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): static
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Ad>
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): static
    {
        if (!$this->ads->contains($ad)) {
            $this->ads->add($ad);
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): static
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): static
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): static
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    #[Route('/ads/{slug}/book', name: 'booking_create')]
    #[IsGranted("ROLE_USER")]
    public function book(Ad $ad,Request $request, EntityManagerInterface $manager): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        // $form = $this->createForm(BookingType::class, $booking, [
        //     'validation_groups' => ['Default','Front']
        // ]);
        $form->handleRequest($request);


        if($form->isSubmitted() && $form->isValid())
        {
            // traitement -> ajouter le user et l'annonce
            $user = $this->getUser();
            $booking->setBooker($user)
                    ->setAd($ad);

            // si les dates ne sont pas disponibles, message d'erreur
            if(!$booking->isBookableDates())
            {
                $this->addFlash('warning',"Les dates que vous avez choisie ne peuvent être réserves: elles sont déjà prises");
            }else{
                $this->addFlash('success',"Merci pour votre réservation");

                $manager->persist($booking);
                $manager->flush();

                return $this->redirectToRoute('booking_show', [
                    'id'=> $booking->getId(),
                    'withAlert' => true
                ]);
            }
        }
        
        return $this->render('booking/book.html.twig', [
            'myForm' => $form->createView(),
            'ad' => $ad
        ]); 
    }

    /**
     * Permet d'afficher la page d'une réservation
     *
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route("/booking/{id}", name:"booking_show")]
    #[IsGranted("ROLE_USER")]
    public function show(Booking $booking, Request $request, EntityManagerInterface $manager): Response
    {   
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());
            
            $manager->persist($comment);
            $manager->flush();

            $this->addFlash('success', 'Votre commentaire a bien été pris en compte');

        }
        
        return $this->render("booking/show.html.twig",[
            'booking' => $booking,
            'myForm' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : {{ad.title}}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.4/dist/css/datepicker.min.css">
{% endblock %}


{% block body %}

    <div class="container full">
        <h1>Réservation de l'annonce: {{ad.title}}</h1>
        <p>Vous êtes sur le point de réserver le bien de <strong>{{ad.author.fullName}}</strong></p>
        {{form_start(myForm)}}
            <div class="bg-light p-3">
                <div class="row">
                    <div class="col">
                        {{form_row(myForm.startDate)}}
                    </div>
                    <div class="col">
                        {{form_row(myForm.endDate)}}
                    </div>
                </div>
            <h4>Montant du séjour: <span id="amount">...</span> &euro;</h4>
            <span id="days">0</span> nuit(s) à {{ad.price}}&euro; / nuit
            <h4 class="mt-3">Vous avez un commentaire?</h4>
                {{form_row(myForm.comment)}}
            </div>
            
            <h2>Vous avez terminé!</h2>
            <button type="submit" class="btn btn-success">Réserver</button>
        {{form_end(myForm)}}
    </div>


{% endblock %}

{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.3.4/dist/js/datepicker.min.js"></script>
    <script>
        const bookingStartDate = document.querySelector("#booking_startDate")
        const bookingEndDate = document.querySelector("#booking_endDate")
        const datePickerStart = new Datepicker(bookingStartDate,{
            format: 'dd/mm/yyyy', // on vient récupérer le jour et on formate la date
            minDate: new Date(),
            datesDisabled: [
               {% for day in ad.notAvailableDays %}
                    "{{day.format('d/m/Y')}}",
               {% endfor %}
            ]// on récupère le tableau de notAvailableDays pour les dates déjà réservée
        })// sur qui on le met , les options // permet d'empêcher de sélectionner les dates avant celle du jour

        const datePickerEnd = new Datepicker(bookingEndDate,{
            format: "dd/mm/yyyy",
            minDate: new Date(),
            datesDisabled: [
               {% for day in ad.notAvailableDays %}
                    "{{day.format('d/m/Y')}}",
               {% endfor %}
            ]
        })

        bookingStartDate.addEventListener('changeDate', ()=>{
            calculateAmount()
        })// changeDate est un event de Datepicker
        
        bookingEndDate.addEventListener('changeDate', ()=>{
            calculateAmount()
        })// changeDate est un event de Datepicker

        const calculateAmount = () => {
            let bookingStartDate =  document.querySelector("#booking_startDate")
            let bookingEndDate = document.querySelector("#booking_endDate")

            const endDate = new Date(bookingEndDate.value.replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'))
            const startDate = new Date(bookingStartDate.value.replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'))

            if(startDate && endDate && startDate < endDate)
            {
                const interval = endDate.getTime() - startDate.getTime()
                const days = interval / (24*60*60*1000)
                const amount = days * {{ad.price}}
                const myDays = document.querySelector("#days")
                const myAmount = document.querySelector("#amount")
                myDays.innerHTML = days
                myAmount.innerHTML = amount.toLocaleString('fr-FR')
            }

        }
    </script>

{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Réservation n°{{booking.id}}{% endblock %}

{% block body %}
    <div class="container">
        <h1>Votre réservation n°{{booking.id}}</h1>
        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo!</h4>
                <p>Votre réservation auprès de <strong><a href="{{path('user_show',{'slug': booking.ad.author.slug})}}">{{booking.ad.author.fullName}}</a></strong></p> pour l'annonce <strong><a href="{{path('ads_show',{'slug': booking.ad.slug})}}">{{booking.ad.title}}</a></strong> a bien étée prise en compte!
            </div>
        {% endif %}
       <div class="row">
            <div class="col ">
                <div class="bg-light p-3">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{booking.id}}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{booking.duration}}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{booking.amount}}&euro;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{booking.comment | raw | nl2br}}</dd>
                    </dl>
                    <hr>
                    <h2>Votre hôte</h2>
                    <div class="row mb-3">
                        <div class="col-3">
                            {% if booking.ad.author.picture %}
                                <img src="/uploads/{{booking.ad.author.picture}}" alt="avatar de {{booking.ad.author.fullName}}" class="avatar avatar-medium">
                            {% else %}
                                <img src="http://placehold.it/300x300" alt="avatar de {{booking.ad.author.fullName}}" class="avatar avatar-medium">
                            {% endif %}
                        </div>
                        <div class="col-9 mb-3">
                            <h4>
                                <a href="{{path('user_show',{'slug': booking.ad.author.slug})}}">{{booking.ad.author.fullName}}</a>
                            </h4>
                            <span class="badge bg-primary">{{booking.ad.author.ads | length}} annonce(s)</span>
                        </div>
                        {{booking.ad.author.description | raw | nl2br}}
                        <a href="{{path('user_show',{'slug': booking.ad.author.slug})}}" class="btn btn-primary">Plus d'info sur {{booking.ad.author.firstName}}</a>
                    </div>
                </div>
                <div class="bg-light p-3" id="comment">
                    <h2>Votre avis compte!</h2>
                    {% if date() > date(booking.endDate) %} {# si la date d'aujourd'hui est plus grande que celle du endDate #}
                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>
                                {{comment.content | nl2br}}
                            </blockquote>
                            <strong>Note: </strong>{% include "partials/rating.html.twig" with {'rating': comment.rating} %}
                        {% else %}
                            {{form_start(myForm)}}

                                {{form_widget(myForm)}}
                                <button type="submit" class="btn btn-success">Confirmer</button>

                            {{form_end(myForm)}}
                        {% endif %}
                        
                    {% else %}
                        <p>Vous ne pourrez pas noter cette annonce tant que votre voyage ne sera pas complet</p>
                    {% endif %}
                    
                </div>
            </div>
            <div class="col">
                <div class="bg-light p-3">
                    <h2>Votre hébergement</h2>
                    <h4>
                        <a href="{{path('ads_show',{'slug': booking.ad.slug})}}">{{booking.ad.title}}</a>
                    </h4>
                    <img src="{{booking.ad.coverImage}}" alt="Image de {{booking.ad.title}}" class="img-fluid">
                    {{booking.ad.content | raw | nl2br }}
                     <a href="{{path('ads_show',{'slug': booking.ad.slug})}}" class="btn btn-primary">Plus d'informations</a>
                </div>
            </div>
        </div>
    </div>


{% endblock %}