src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use App\Entity\Comment;
use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use App\Repository\AdRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: AdRepository::class)]
#[ORM\HasLifecycleCallbacks] // on vient chercher les events qui permettent d'agir avant ou après le persist
#[UniqueEntity(fields:['title'], message:"Une autre annonce possède déjà ce titre merci de le modifier")]
class Ad
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Lenght(min:10, max:255, minMessage:"Le titre doit faire plus de 10 caractères", maxMessage:"Le titre ne doit pas faire plus de 255 caractères")]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min:20, max:255, minMessage:"L'introduction doit faire plus de 20 caractères", maxMessage:"L'introduction ne doit pas faire plus de 255 caractères")]
    private ?string $introduction = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min:100, minMessage:'Votre description doit faire plus de 100 caractères')]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    #[Assert\Url(message: "Il faut une URL valide")]
    private ?string $coverImage = null;

    #[ORM\Column]
    private ?int $rooms = null;

    #[ORM\OneToMany(mappedBy: 'ad', targetEntity: Image::class, orphanRemoval: true)]
    #[Assert\Valid()]
    private Collection $images;

    #[ORM\ManyToOne(inversedBy: 'ads')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\OneToMany(mappedBy: 'ad', targetEntity: Booking::class)]
    private Collection $bookings;

    #[ORM\OneToMany(mappedBy: 'ad', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug automatiquement si on ne le donne pas
     *
     * @return void
     */
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug(): void 
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet d'obtenir un tableau de jour qui ne sont pas disponible pour cette annonce
     *
     * @return array|null Un tableau d'objet DateTime réprésentant les jours d'occupation
     */
    public function getNotAvailableDays(): ?array 
    {
        $notAvailableDays = [];
        foreach($this->bookings as $booking)
        {
            // calculer les jours qui se trouvent entre la date d'arrivée et de départ
            //fonction range() de php permet de créer un tableu qui contient chaque étape existante entre 2 nombres
            //$result = range(10,20,2) // nombre de départ , nombre d'arrivée , calcule les étapes en travaillant par 2
            //reponse = [10,12,14,16,18,20]
            $resultat = range($booking->getStartDate()->getTimestamp(),$booking->getEndDate()->getTimestamp(),24*60*60);
            //[23132123,23132123,23132123,23132123]
            $days = array_map(function($daysTimestamp){
                return new \DateTime(date('Y-m-d',$daysTimestamp)); // on formate en année mois jour
            },$resultat);

            $notAvailableDays = array_merge($notAvailableDays,$days); // fusionne 2 tableaux
        }
        return $notAvailableDays;
    }

    /**
     * Permet de récupérer la note d'une annonce
     *
     * @return integer
     */
    public function getAvgRatings(): int
    {
        //calculer la somme des notations
        //la fonction array_reduce permet de réduire le tableau à une seule valeur ( attention il faut un tableau pas une array Collection )1er paramètre c'est le tableau à réduire en 2éme paramètre de la fonction c'est la fonction à faire pour chaque valeur, 3ème c'est la valeur par défaut
        $sum = array_reduce($this->comments->toArray(),function($total,$comment){
            return $total + $comment->getRating();
        },0);

        // faire la division pour avoir la moyenne (ternaire)
        if(count($this->comments)>0) return $moyenne = round($sum/count($this->comments)); // si $this->comments est supérieur à 0 il y a plusieurs commentaires

        return 0;
    }

    /**
     * Permet de récupérer le commentaire d'un author par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author): ?Comment
    {
        foreach($this->comments as $comment)
        {
            if($comment->getAuthor() === $author) return $comment;
        }

        return null;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): static
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): static
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): static
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): static
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): static
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields:['email'],message: "Un autre utilisateur possède déjà cette adresse e-mail, merci de la modifier")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(message: "Veuillez renseigner une adresse e-mail valide")]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotBlank(message:"Veuillez renseigner un mot de passe")] // on ne peut pas le laisser vide
    private ?string $password = null;

    #[Assert\EqualTo(propertyPath:"password", message:"Vous n'avez pas correctement confirmé votre mot de passe")]
    public ?string $passwordConfirm = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Veuillez renseigner votre prénom")]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Veuillez renseigner votre nom de famille")]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Image(mimeTypes:['image/png','image/jpeg', 'image/jpg', 'image/gif'], mimeTypesMessage:"Vous devez upload un fichier jpg, jpeg, png ou gif")]
    #[Assert\File(maxSize:"1024k", maxSizeMessage: "La taille du fichier est trop grande")]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min:10,max:255, minMessage:"Votre introduction doit faire plus de 10 caractères", maxMessage:"Votre introduction ne doit pas faire plus de 255 caractères")]
    private ?string $introduction = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min:100, minMessage:"Votre description doit faire plus de 100 caractères")]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Ad::class)]
    private Collection $ads;

    #[ORM\OneToMany(mappedBy: 'booker', targetEntity: Booking::class)]
    private Collection $bookings;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet de créer un slug automatiquement avec le nom et prénom de l'utilisateur
     *
     * @return void
     */
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug(): void
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName.' '.uniqid());
        }
    }

    /**
     * Permet d'obtenir le nom complet de l'utilisateur
     *
     * @return string
     */
    public function getFullName(): string
    {
        return $this->firstName." ".$this->lastName;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): static
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Ad>
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): static
    {
        if (!$this->ads->contains($ad)) {
            $this->ads->add($ad);
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): static
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): static
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): static
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug':ad.slug}) %} {# on vient faire un set pour ne pas devoir écrire dans chaque lien notre url (ne pas se répéter) on doit lui donner le paramètre slug et pour ce paramètre on lui donne le ad.slug #}
<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ad.rooms}} chambres, <strong>{{ad.price}}€ / nuit</strong>
            <br>
            {% if ad.comments | length > 0 %}
                {% include "partials/rating.html.twig" with {'rating':ad.avgRatings} %}
                ( {{ad.comments | length}} avis )
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
            
        </div>
        <a href="{{url}}">
            <img src="{{ad.coverImage}}" alt="Image de l'annonce {{ad.title}}" class="starsimg">
        </a>
        <div class="card-body">
            <h4 class="card-title">{{ad.title}}</h4>
            <p class="card-text">{{ad.introduction}}</p>
            <a href="{{url}}" class="btn btn-secondary">En savoir plus</a>
        </div>
    </div>

</div>

templates/ad/_collection.html.twig
{% block _annonce_images_widget %}
    {# Définition du champ annonce_image, la variable form correspond au hamp annonce_image #}
    <p>Ici, vous pouvez ajouter vos propres images</p>
    {{form_widget(form)}}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">Ajouter une image</button>
    </div> 

{% endblock %}

{% block _annonce_images_entry_row %}
    {{form_widget(form)}}
{% endblock %}

{% block _annonce_images_entry_widget %}
    <div class="form-group my-2" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{form_widget(form.url)}}
                        {{form_errors(form.url)}}
                    </div>
                    <div class="col">
                        {{form_widget(form.caption)}}
                        {{form_errors(form.caption)}}</div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" class="btn btn-danger" data-action="delete" data-target="#block_{{id}}">X</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}


{% block title %}Modification de l'annonce: {{ad.title}}{% endblock %}

{% form_theme myForm 'ad/_collection.html.twig' %} {# on ne lui donne plus le _self mais le fichier qu'on a créer avec la mise en forme du formulaire pour ne pas faire de répétition #}

{% block body %}

    <div class="container">
        <h1>Modification de l'annonce : <strong>{{ad.title}}</strong></h1>
    
        {{form_start(myForm)}}

            {{form_widget(myForm)}}
            <button type="submit" class="btn btn-warning mt-3">Modifier</button>


        {{form_end(myForm)}}


    </div>

{% endblock %}

{% block javascripts %}
    {# on a mit le contenu dans assets/js/ad.js pour ne pas se répéter et avoir uniquement un fichier qu'on répète #}
    {{encore_entry_script_tags('annonce')}} 
    {# on vient chercher le code qu'on a externaliser (Attention ne pas oublier dans webpack config le addEntry de notre fichier externe) #}
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Annonces{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            {% for ad in ads  %}
                {% include "ad/_ad.html.twig" %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une annonce{% endblock %}

 {% form_theme myForm 'ad/_collection.html.twig' %} {# on vient lui donner un theme, on impose un template à twig , pour qui (myForm) , quel theme ( _self -> on créer notre propre thème)  #}
{# dans 'bootstrap_5_layout.html.twig' on vient chercher un thème prédéfini #}

{% block body %}
    <div class="container">
        <h1>Création d'une nouvelle annonce</h1>

        {{form_start(myForm)}}

        

            {# {{form_widget(myForm.title, {'attr':{'class':'form-control'}})}} #}

            {# {{form_row(myForm.title)}} #}

            {# Méthode pour créer le bouton dans le form ( mais à l'extérieur de sa création) #}

            {{form_widget(myForm)}}



            <button type="submit" class="btn btn-primary mt-3">Création d'une annonce</button>

        {{form_end(myForm)}}
    </div>

{% endblock %}

{# mode templatink on vient créer notre template ( mise en form de notre formulaire ) #}
{# {% block form_row %} #}
{#     
    <div class="form-group">
        <div class="row">
            <div class="col-6"> #}
                {# {{form_label(form)}} #}
                {# form fait référence à tout le formulaire pour notre template , non prédéfinis il ne fait pas référence à myForm directement #}
            {# </div>
            <div class="col-6">
                {{form_widget(form)}} #}
            {# </div>
        </div>
    </div> #}

{# {% endblock %} #}

{# {% block text_widget %}  #}
{# on vient templater tout les inputs type text #}

    {# <input type="text" name="{{full_name}}" id="{{id}}" class="form-control"> #}

{# 
{% endblock %} #}

{% block javascripts %}
    {# on a mit le contenu dans assets/js/ad.js pour ne pas se répéter et avoir uniquement un fichier qu'on répète #}
    {{encore_entry_script_tags('annonce')}}
{% endblock %}

templates/ad/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Annonce: {{ad.title}}{% endblock %}

{% block body %}
    <div class="annonce-title" style="background-image:url({{ad.coverImage}})">
        <div class="container">
            <h1>{{ad.title}}</h1>
            <p>{{ad.introduction}}</p>
            <p class="h2"><strong>{{ad.rooms}} chambres</strong> pour <strong>{{ad.price}}€ par nuit</strong></p>
            <a href="{{path('booking_create',{'slug' :ad.slug})}}" class="btn btn-primary">Réserver</a>
            {% if (app.user and app.user == ad.author) or is_granted('ROLE_ADMIN') %}
                <a href="{{path('ads_edit', {'slug':ad.slug})}}" class="btn btn-warning">Modification de l'annonce</a>
                <a href="{{path('ads_delete', {'slug':ad.slug})}}" class="btn btn-danger">Supprimer l'annonce</a>
            {% endif %}
            
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ad.content | raw | nl2br}}{# raw est un filtre qui laisse passer le html sinon twig vient le bloquer et l'affiche comme du simple texte , nl2br permet de garder les espacements#}

                <div class="bd-example">
                    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
                        <div class="carousel-indicators">
                        {% for image in ad.images %}
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{loop.index0}}" {% if loop.first %} class="active" aria-current="true" {% endif %} aria-label="Slide {{loop.index}}"></button>
                        {% endfor %} 
                           
                        </div>
                        <div class="carousel-inner">
                            {% for image in ad.images %}
                                <div class="carousel-item {% if loop.first %}active{% endif %}">
                                    <img src="{{image.url}}" class="d-block w-100" alt="image de {{ad.title}}">
                                    <div class="carousel-caption d-none d-md-block">
                                         <h5>{{ad.title}}</h5>
                                        <p>{{image.caption}}</p>
                                    </div>
                                </div>
                            {% endfor %}
                           
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
                {# gestion des commentaire #}
                <hr>
                {% if ad.comments | length > 0 %}
                    <h2 class='mb-3'>Commentaires de nos locataires</h2>
                    <div class="alert alert-info">
                        <h4 class='alert-heading text-center'>
                            <div class="row align-items-center">
                                <div class="col">
                                    Note globale
                                </div>
                                <div class="col">
                                    {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
                                    <br>
                                    <small>(cette moyenne est calculée sur {{ad.comments | length}} avis)</small>
                                </div>
                            </div>
                        </h4>
                    </div>
                    {% for comment in ad.comments %}
                        <div class="bg-light mb-3 p-3">
                            <strong>{{comment.author.firstName}}</strong> a dit: 
                            <blockquote>
                                {{comment.content | nl2br}}
                            </blockquote>
                            <strong>Note donnée: </strong>
                            {% include "partials/rating.html.twig" with {'rating': comment.rating} %}                        
                        </div>
                    {% endfor %}
                {% else %}
                    <h2>Cette annonce n'a pas encore reçu de commentaire...</h2>
                {% endif %}
                
            </div>    

            <div class="col">
            {% set a = ad.author %} {# permet de ne pas devoir répéter ad.author mais juste le a. #}
                <div class="row">
                    <div class="col-3">
                        <a href="{{path('user_show', {'slug': a.slug})}}">
                            {% if a.picture %}
                                <img src="/uploads/{{a.picture}}" alt="Avatar de {{a.fullName}}" class="avatar avatar-medium">
                            {% else %}
                                <img src="http://placehold.it/300x300" alt="Avatar de {{a.fullName}}" class="avatar avatar-medium">
                            {% endif %}
                            
                        </a>
                    </div>
                    <div class="col">
                    <a href="{{path('user_show', {'slug': a.slug})}}" class="text-black">
                        <h3>{{a.fullName}}</h3>
                    </a>
                    <button type="button" class="btn btn-primary">
                        <span class="badge badge-secondary">Annonce(s) : {{a.ads | length}}</span>
                    </button>
                    </div>
                    {{a.description | raw | nl2br}}
                </div>
            </div>
        </div>
    </div>    
{% endblock %}

{% block javascripts %}

    {# pour récup ce qu'il y a dans le parent sur la base que l'on extends #}
    {{parent()}}

    <script>
        console.log('je suis dans show.html.twig')
    </script>

{% endblock %}